version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:12
steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
        paths:
          - node_modules
          - ~/.npm 
          - ~/.cache
        key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test