version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      build:
        docker:
          - image: circleci/node:12
        steps:
          - checkout
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
          - run: 
              name: Install
              command: npm install 
          - save_cache:
              paths:
                - node_modules
              key: v1-dependencies-{{ checksum "package.lock" }}
          - run:
              name: Test
              command: npm test